name: Docker build and push

on:
  pull_request:
    branches:
      - master

  push:
    branches:
      - master

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Checkout library
        uses: actions/checkout@v3
        with:
          repository: lilymammadova/JPA-starter
          path: jpa-starter

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and Install Jpa Starter
        run: |
          cd jpa-starter
          mvn clean install
          cd ..

      - name: Package Jar
        run: mvn package -DskipTests

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}/hotel-app:latest .

      - name: Authenticate with GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: lilymammadova
          password: ${{ secrets.ORG_PAT }}

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}/hotel-app:latest