name: CI/CD with Jar Build and Test

on:
  pull_request:
    branches:
      - master

  push:
    branches:
      - master

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checkout library
        uses: actions/checkout@v2
        with:
          repository: lilymammadova/JPA-starter
          ref: add_jpa_starter
          path: jpa-starter

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and Install Jpa Starter
        run: |
          cd jpa-starter
          mvn clean install
          cd ..

      - name: Build and Test
        run: mvn -B clean install

      - name: Package Jar
        run: mvn package

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hotelapp.jar
          path: target/*.jar
